### PR TITLE
Use current instance when checking if storedCartWithIdentifierExists

### LINKED ISSUE #95: Instance is ignored on cart::instance('another')->store()
I have to implement persistent cart and wishlist for a site, store(), restore() functions working fine for the cart instance created first for each identifier, however another instance can't be stored.

image

As I see, the following function called within store() throwing CartAlreadyStoredException (message: "a cart with identifier {$identifier} was already stored") ignoreds the instance for the class:

private function storedCartWithIdentifierExists($identifier) {

return $this->getConnection()->table($this->getTableName())->where('identifier', $identifier)->exists();

}

To handle multiple instances the function would be right if ->where('instance', $this->currentInstance()) added like:

private function storedCartWithIdentifierExists($identifier) {

return $this->getConnection()->table($this->getTableName())->where('identifier', $identifier)->where('instance', $this->currentInstance())->exists();

}

Thanks, keep up the good work!

### PR DESCRIPTION
**Pull request by Norris1z**
This PR checks if there are multiple instances and uses the current instance when checking if storedCartWithIdentifierExists. This fixes #95

### CODE REVIEW

**Review by gabrielmoura — APPROVED** [review]
That fixed the problem, I was already giving up on the app.

File: src/Cart.php [hunk 1]
```diff
@@ -831,7 +831,12 @@ private function isMulti($item)
      */
     private function storedCartWithIdentifierExists($identifier)
     {
-        return $this->getConnection()->table($this->getTableName())->where('identifier', $identifier)->exists();
+        $data = ['identifier' => $identifier];
+        if ($this->countInstances() > 1) {
```
Comment (bumbummen99) [inline src/Cart.php:835]: `countInstances` does count the Items in the cart. This methods should be called `countItems()` imo.
Also why is it relevant how many items the cart has for checking the configured instance, for example if i start with an empty cart?

File: tests/CartTest.php [hunk 2]
```diff
@@ -1453,4 +1453,34 @@ private function setConfigFormat($decimals, $decimalPoint, $thousandSeperator)
...
+        $newInstance->instance($instanceName = 'someinstance');
+        $newInstance->add(new BuyableProduct());
+        $newInstance->store($newIdentifier = 456);
+        $newInstanceSerialized = serialize($newInstance->content());
+
+        $this->assertDatabaseHas('shoppingcart', ['identifier' => $identifier, 'instance' => 'default', 'content' => $serialized]);
+
+        $this->assertDatabaseHas('shoppingcart', ['identifier' => $newIdentifier, 'instance' => $instanceName, 'content' => $newInstanceSerialized]);
+
+        Event::assertDispatched('cart.stored');
```
Comment (bumbummen99) [inline tests/CartTest.php:1484]: I think this event should be checked directly after each call to `->store()`

File: tests/CartTest.php [hunk 3]
```diff
@@ -1453,4 +1453,34 @@ private function setConfigFormat($decimals, $decimalPoint, $thousandSeperator)
...
+        $cart->add(new BuyableProduct());
+
+        $cart->store($identifier = 123);
+
+        $serialized = serialize($cart->content());
+
+        $newInstance = $this->getCart();
+        $newInstance->instance($instanceName = 'someinstance');
+        $newInstance->add(new BuyableProduct());
+        $newInstance->store($newIdentifier = 456);
```
Comment (bumbummen99) [inline tests/CartTest.php:1477]: Wouldn't it be better to use the same identifier here to make sure the instance does get checked correctly?

File: src/Cart.php [hunk 4]
```diff
@@ -831,7 +831,12 @@ private function isMulti($item)
      */
     private function storedCartWithIdentifierExists($identifier)
```
Comment (bumbummen99) [inline src/Cart.php:832]: Maybe we should rename this method since it then would also check for the instance.

**Review by bumbummen99 — CHANGES_REQUESTED** [review]

File: src/Cart.php (hunk 1 above)
Comment (Norris1z) [reply src/Cart.php:835]: I agree with you that the `countInstances` method should be called `countItems`. The name is quite misleading. The idea was to check the number of instances being set up by the user. I could have done ` $this->getConnection()->table($this->getTableName())->where(['identifier' => $identifier, 'instance'=> $this->currentInstance()])->exists()` but this breaks some tests

File: src/Cart.php (hunk 4 above)
Comment (Norris1z) [reply src/Cart.php:832]:
```php
private function storedCartWithIdentifierExists($identifier)
{
    return $this->getConnection()->table($this->getTableName())->where(['identifier' => $identifier, 'instance'=> $this->currentInstance()])->exists();
}
```
Using the current instance directly breaks the `merge` method too.

```php
$cart = $this->getCartDiscount(50);
$cart->add(new BuyableProduct(1, 'Item', 10.00), 1);
$cart->add(new BuyableProduct(2, 'Item 2', 10.00), 1);
$cart->store('test');

$cart2 = $this->getCart();
$cart2->instance('test2');
$cart2->setGlobalTax(0);
$cart2->setGlobalDiscount(0);

$this->assertEquals('0', $cart2->countInstances());
$cart2->merge('test');
$this->assertEquals('2', $cart2->countInstances()); // count is still 0
```
The items in `$cart` are not merged into `$cart2` because the `merge` method checks if the cart to be merged is also of the same instance.

```php
public function merge($identifier, $keepDiscount = false, $keepTax = false, $dispatchAdd = true)
{
    if (!$this->storedCartWithIdentifierExists($identifier)) { //should pass an instance name to this method imo
        return false;
    }

    $stored = $this->getConnection()->table($this->getTableName())
        ->where(['identifier'=> $identifier,'instance'=>$this->currentInstance()])->first(); //i added the instance to it

    $storedContent = unserialize($stored->content);

     foreach ($storedContent as $cartItem) {
         $this->addCartItem($cartItem, $keepDiscount, $keepTax, $dispatchAdd);
     }

    $this->events->dispatch('cart.merged');

     return true;
}
```

Fixing this means we'll have to change the signature of the `storedCartWithIdentifierExists` method to something like `storedCartWithIdentifierExists($instance,$identifier)` this way we can pass the instance of the cart to be merged too.

I think we should pass the instance as the last parameter with a default value to avoid a breaking change.

**Review by bumbummen99 — APPROVED** [review]
Alright that looks good, thanks for also changing the Readme <3 Sorry for the late review
